# https://taskfile.dev
version: '3'

tasks:
  list:
    aliases: [default]
    cmds:
      - task --list-all

  setup:
    cmds:
      - pnpm install

  dev:
    cmds:
      - pnpm run vite

  build:
    deps: [typecheck]
    cmds:
      - pnpm run vite build

  typecheck:
    cmds:
      - pnpm run tsc -b

  check:
    cmds:
      - pnpm run biome check --write .

  api:
    cmds:
      - pnpm run openapi-ts

  deploy:liara:
    deps: [build]
    desc: Deploy frontend to Liara
    env:
      LIARA_TOKEN:
        required: true
    cmds:
      - pnpm i -g @liara/cli
      - |
        liara deploy \
          --api-token="$LIARA_TOKEN" \
          --no-app-logs \
          --app="b85" \
          --build-location="iran"
