# https://taskfile.dev
version: '3'

dotenv: ['../.env']

tasks:
  list:
    aliases: [default]
    cmds:
      - task --list-all

  setup:
    cmds:
      - pnpm install

  dev:web:
    aliases: [dev]
    cmds:
      - pnpm run vite --port {{.FRONTEND_PORT}}

  dev:tauri:
    cmds:
      - pnpm run tauri dev

  build:
    deps: [typecheck]
    cmds:
      - pnpm run vite build

  typecheck:
    cmds:
      - pnpm run tsc -b

  check:
    cmds:
      - pnpm run biome check --write .

  api:
    cmds:
      - pnpm run openapi-ts

  ci:deploy:
    desc: Deploy frontend (to Liara)
    requires:
      vars: [LIARA_API_TOKEN]
    cmds:
      - |
        pnpm run liara deploy \
          --api-token="$LIARA_API_TOKEN" \
          --path=./dist/ \
          --no-app-logs \
          --app="b85" \
          --build-location="iran" ;
