/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsWorkTimerRouteRouteImport } from './routes/apps/work-timer/route'
import { Route as AppsRakatRouteRouteImport } from './routes/apps/rakat/route'
import { Route as AppsRakatIndexRouteImport } from './routes/apps/rakat/index'
import { Route as AppsNebulaIndexRouteImport } from './routes/apps/nebula/index'
import { Route as AppsRakatPrayRouteImport } from './routes/apps/rakat/pray'
import { Route as AppsRakatChooseRouteImport } from './routes/apps/rakat/choose'
import { Route as AppsWorkTimerTotalIndexRouteImport } from './routes/apps/work-timer/total/index'
import { Route as AppsWorkTimerSettingsIndexRouteImport } from './routes/apps/work-timer/settings/index'
import { Route as AppsWorkTimerhomeIndexRouteImport } from './routes/apps/work-timer/(home)/index'
import { Route as AppsNamoratabhomeIndexRouteImport } from './routes/apps/namoratab/(home)/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsWorkTimerRouteRoute = AppsWorkTimerRouteRouteImport.update({
  id: '/apps/work-timer',
  path: '/apps/work-timer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRakatRouteRoute = AppsRakatRouteRouteImport.update({
  id: '/apps/rakat',
  path: '/apps/rakat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRakatIndexRoute = AppsRakatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRakatRouteRoute,
} as any)
const AppsNebulaIndexRoute = AppsNebulaIndexRouteImport.update({
  id: '/apps/nebula/',
  path: '/apps/nebula/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRakatPrayRoute = AppsRakatPrayRouteImport.update({
  id: '/pray',
  path: '/pray',
  getParentRoute: () => AppsRakatRouteRoute,
} as any)
const AppsRakatChooseRoute = AppsRakatChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => AppsRakatRouteRoute,
} as any)
const AppsWorkTimerTotalIndexRoute = AppsWorkTimerTotalIndexRouteImport.update({
  id: '/total/',
  path: '/total/',
  getParentRoute: () => AppsWorkTimerRouteRoute,
} as any)
const AppsWorkTimerSettingsIndexRoute =
  AppsWorkTimerSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppsWorkTimerRouteRoute,
  } as any)
const AppsWorkTimerhomeIndexRoute = AppsWorkTimerhomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AppsWorkTimerRouteRoute,
} as any)
const AppsNamoratabhomeIndexRoute = AppsNamoratabhomeIndexRouteImport.update({
  id: '/apps/namoratab/(home)/',
  path: '/apps/namoratab/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/rakat': typeof AppsRakatRouteRouteWithChildren
  '/apps/work-timer': typeof AppsWorkTimerRouteRouteWithChildren
  '/apps/rakat/choose': typeof AppsRakatChooseRoute
  '/apps/rakat/pray': typeof AppsRakatPrayRoute
  '/apps/nebula': typeof AppsNebulaIndexRoute
  '/apps/rakat/': typeof AppsRakatIndexRoute
  '/apps/namoratab': typeof AppsNamoratabhomeIndexRoute
  '/apps/work-timer/': typeof AppsWorkTimerhomeIndexRoute
  '/apps/work-timer/settings': typeof AppsWorkTimerSettingsIndexRoute
  '/apps/work-timer/total': typeof AppsWorkTimerTotalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/rakat/choose': typeof AppsRakatChooseRoute
  '/apps/rakat/pray': typeof AppsRakatPrayRoute
  '/apps/nebula': typeof AppsNebulaIndexRoute
  '/apps/rakat': typeof AppsRakatIndexRoute
  '/apps/namoratab': typeof AppsNamoratabhomeIndexRoute
  '/apps/work-timer': typeof AppsWorkTimerhomeIndexRoute
  '/apps/work-timer/settings': typeof AppsWorkTimerSettingsIndexRoute
  '/apps/work-timer/total': typeof AppsWorkTimerTotalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/rakat': typeof AppsRakatRouteRouteWithChildren
  '/apps/work-timer': typeof AppsWorkTimerRouteRouteWithChildren
  '/apps/rakat/choose': typeof AppsRakatChooseRoute
  '/apps/rakat/pray': typeof AppsRakatPrayRoute
  '/apps/nebula/': typeof AppsNebulaIndexRoute
  '/apps/rakat/': typeof AppsRakatIndexRoute
  '/apps/namoratab/(home)/': typeof AppsNamoratabhomeIndexRoute
  '/apps/work-timer/(home)/': typeof AppsWorkTimerhomeIndexRoute
  '/apps/work-timer/settings/': typeof AppsWorkTimerSettingsIndexRoute
  '/apps/work-timer/total/': typeof AppsWorkTimerTotalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps/rakat'
    | '/apps/work-timer'
    | '/apps/rakat/choose'
    | '/apps/rakat/pray'
    | '/apps/nebula'
    | '/apps/rakat/'
    | '/apps/namoratab'
    | '/apps/work-timer/'
    | '/apps/work-timer/settings'
    | '/apps/work-timer/total'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps/rakat/choose'
    | '/apps/rakat/pray'
    | '/apps/nebula'
    | '/apps/rakat'
    | '/apps/namoratab'
    | '/apps/work-timer'
    | '/apps/work-timer/settings'
    | '/apps/work-timer/total'
  id:
    | '__root__'
    | '/'
    | '/apps/rakat'
    | '/apps/work-timer'
    | '/apps/rakat/choose'
    | '/apps/rakat/pray'
    | '/apps/nebula/'
    | '/apps/rakat/'
    | '/apps/namoratab/(home)/'
    | '/apps/work-timer/(home)/'
    | '/apps/work-timer/settings/'
    | '/apps/work-timer/total/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRakatRouteRoute: typeof AppsRakatRouteRouteWithChildren
  AppsWorkTimerRouteRoute: typeof AppsWorkTimerRouteRouteWithChildren
  AppsNebulaIndexRoute: typeof AppsNebulaIndexRoute
  AppsNamoratabhomeIndexRoute: typeof AppsNamoratabhomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/work-timer': {
      id: '/apps/work-timer'
      path: '/apps/work-timer'
      fullPath: '/apps/work-timer'
      preLoaderRoute: typeof AppsWorkTimerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/rakat': {
      id: '/apps/rakat'
      path: '/apps/rakat'
      fullPath: '/apps/rakat'
      preLoaderRoute: typeof AppsRakatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/rakat/': {
      id: '/apps/rakat/'
      path: '/'
      fullPath: '/apps/rakat/'
      preLoaderRoute: typeof AppsRakatIndexRouteImport
      parentRoute: typeof AppsRakatRouteRoute
    }
    '/apps/nebula/': {
      id: '/apps/nebula/'
      path: '/apps/nebula'
      fullPath: '/apps/nebula'
      preLoaderRoute: typeof AppsNebulaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/rakat/pray': {
      id: '/apps/rakat/pray'
      path: '/pray'
      fullPath: '/apps/rakat/pray'
      preLoaderRoute: typeof AppsRakatPrayRouteImport
      parentRoute: typeof AppsRakatRouteRoute
    }
    '/apps/rakat/choose': {
      id: '/apps/rakat/choose'
      path: '/choose'
      fullPath: '/apps/rakat/choose'
      preLoaderRoute: typeof AppsRakatChooseRouteImport
      parentRoute: typeof AppsRakatRouteRoute
    }
    '/apps/work-timer/total/': {
      id: '/apps/work-timer/total/'
      path: '/total'
      fullPath: '/apps/work-timer/total'
      preLoaderRoute: typeof AppsWorkTimerTotalIndexRouteImport
      parentRoute: typeof AppsWorkTimerRouteRoute
    }
    '/apps/work-timer/settings/': {
      id: '/apps/work-timer/settings/'
      path: '/settings'
      fullPath: '/apps/work-timer/settings'
      preLoaderRoute: typeof AppsWorkTimerSettingsIndexRouteImport
      parentRoute: typeof AppsWorkTimerRouteRoute
    }
    '/apps/work-timer/(home)/': {
      id: '/apps/work-timer/(home)/'
      path: '/'
      fullPath: '/apps/work-timer/'
      preLoaderRoute: typeof AppsWorkTimerhomeIndexRouteImport
      parentRoute: typeof AppsWorkTimerRouteRoute
    }
    '/apps/namoratab/(home)/': {
      id: '/apps/namoratab/(home)/'
      path: '/apps/namoratab'
      fullPath: '/apps/namoratab'
      preLoaderRoute: typeof AppsNamoratabhomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppsRakatRouteRouteChildren {
  AppsRakatChooseRoute: typeof AppsRakatChooseRoute
  AppsRakatPrayRoute: typeof AppsRakatPrayRoute
  AppsRakatIndexRoute: typeof AppsRakatIndexRoute
}

const AppsRakatRouteRouteChildren: AppsRakatRouteRouteChildren = {
  AppsRakatChooseRoute: AppsRakatChooseRoute,
  AppsRakatPrayRoute: AppsRakatPrayRoute,
  AppsRakatIndexRoute: AppsRakatIndexRoute,
}

const AppsRakatRouteRouteWithChildren = AppsRakatRouteRoute._addFileChildren(
  AppsRakatRouteRouteChildren,
)

interface AppsWorkTimerRouteRouteChildren {
  AppsWorkTimerhomeIndexRoute: typeof AppsWorkTimerhomeIndexRoute
  AppsWorkTimerSettingsIndexRoute: typeof AppsWorkTimerSettingsIndexRoute
  AppsWorkTimerTotalIndexRoute: typeof AppsWorkTimerTotalIndexRoute
}

const AppsWorkTimerRouteRouteChildren: AppsWorkTimerRouteRouteChildren = {
  AppsWorkTimerhomeIndexRoute: AppsWorkTimerhomeIndexRoute,
  AppsWorkTimerSettingsIndexRoute: AppsWorkTimerSettingsIndexRoute,
  AppsWorkTimerTotalIndexRoute: AppsWorkTimerTotalIndexRoute,
}

const AppsWorkTimerRouteRouteWithChildren =
  AppsWorkTimerRouteRoute._addFileChildren(AppsWorkTimerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRakatRouteRoute: AppsRakatRouteRouteWithChildren,
  AppsWorkTimerRouteRoute: AppsWorkTimerRouteRouteWithChildren,
  AppsNebulaIndexRoute: AppsNebulaIndexRoute,
  AppsNamoratabhomeIndexRoute: AppsNamoratabhomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
