CREATE DATABASE IF NOT EXISTS b85;

USE b85;

DROP TABLE IF EXISTS clicks;
DROP TABLE IF EXISTS links;

CREATE TABLE LINKS (
  linkId INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  originalUrl VARCHAR(255) NOT NULL,
  shortCode VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE CLICKS (
  clickId INT PRIMARY KEY AUTO_INCREMENT,
  createdAt DATETIME NOT NULL DEFAULT NOW(),
  linkId INT NOT NULL,
  FOREIGN KEY fkClicksLinks (linkId)
    REFERENCES links (linkId)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
