/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppsPromptorRouteImport } from "./routes/apps/promptor"
import { Route as AppsPickOneRouteImport } from "./routes/apps/pick-one"
import { Route as AppsNebulaRouteImport } from "./routes/apps/nebula"
import { Route as AppsWorkTimerRouteRouteImport } from "./routes/apps/work-timer/route"
import { Route as AppsRakatRouteRouteImport } from "./routes/apps/rakat/route"
import { Route as AppsWorkTimerIndexRouteImport } from "./routes/apps/work-timer/index"
import { Route as AppsRakatIndexRouteImport } from "./routes/apps/rakat/index"
import { Route as AppsWorkTimerTotalRouteImport } from "./routes/apps/work-timer/total"
import { Route as AppsWorkTimerSettingsRouteImport } from "./routes/apps/work-timer/settings"
import { Route as AppsRakatPrayRouteImport } from "./routes/apps/rakat/pray"
import { Route as AppsRakatChooseRouteImport } from "./routes/apps/rakat/choose"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPromptorRoute = AppsPromptorRouteImport.update({
  id: "/apps/promptor",
  path: "/apps/promptor",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPickOneRoute = AppsPickOneRouteImport.update({
  id: "/apps/pick-one",
  path: "/apps/pick-one",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsNebulaRoute = AppsNebulaRouteImport.update({
  id: "/apps/nebula",
  path: "/apps/nebula",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsWorkTimerRouteRoute = AppsWorkTimerRouteRouteImport.update({
  id: "/apps/work-timer",
  path: "/apps/work-timer",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRakatRouteRoute = AppsRakatRouteRouteImport.update({
  id: "/apps/rakat",
  path: "/apps/rakat",
  getParentRoute: () => rootRouteImport,
} as any)
const AppsWorkTimerIndexRoute = AppsWorkTimerIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppsWorkTimerRouteRoute,
} as any)
const AppsRakatIndexRoute = AppsRakatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppsRakatRouteRoute,
} as any)
const AppsWorkTimerTotalRoute = AppsWorkTimerTotalRouteImport.update({
  id: "/total",
  path: "/total",
  getParentRoute: () => AppsWorkTimerRouteRoute,
} as any)
const AppsWorkTimerSettingsRoute = AppsWorkTimerSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppsWorkTimerRouteRoute,
} as any)
const AppsRakatPrayRoute = AppsRakatPrayRouteImport.update({
  id: "/pray",
  path: "/pray",
  getParentRoute: () => AppsRakatRouteRoute,
} as any)
const AppsRakatChooseRoute = AppsRakatChooseRouteImport.update({
  id: "/choose",
  path: "/choose",
  getParentRoute: () => AppsRakatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/apps/rakat": typeof AppsRakatRouteRouteWithChildren
  "/apps/work-timer": typeof AppsWorkTimerRouteRouteWithChildren
  "/apps/nebula": typeof AppsNebulaRoute
  "/apps/pick-one": typeof AppsPickOneRoute
  "/apps/promptor": typeof AppsPromptorRoute
  "/apps/rakat/choose": typeof AppsRakatChooseRoute
  "/apps/rakat/pray": typeof AppsRakatPrayRoute
  "/apps/work-timer/settings": typeof AppsWorkTimerSettingsRoute
  "/apps/work-timer/total": typeof AppsWorkTimerTotalRoute
  "/apps/rakat/": typeof AppsRakatIndexRoute
  "/apps/work-timer/": typeof AppsWorkTimerIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/apps/nebula": typeof AppsNebulaRoute
  "/apps/pick-one": typeof AppsPickOneRoute
  "/apps/promptor": typeof AppsPromptorRoute
  "/apps/rakat/choose": typeof AppsRakatChooseRoute
  "/apps/rakat/pray": typeof AppsRakatPrayRoute
  "/apps/work-timer/settings": typeof AppsWorkTimerSettingsRoute
  "/apps/work-timer/total": typeof AppsWorkTimerTotalRoute
  "/apps/rakat": typeof AppsRakatIndexRoute
  "/apps/work-timer": typeof AppsWorkTimerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/apps/rakat": typeof AppsRakatRouteRouteWithChildren
  "/apps/work-timer": typeof AppsWorkTimerRouteRouteWithChildren
  "/apps/nebula": typeof AppsNebulaRoute
  "/apps/pick-one": typeof AppsPickOneRoute
  "/apps/promptor": typeof AppsPromptorRoute
  "/apps/rakat/choose": typeof AppsRakatChooseRoute
  "/apps/rakat/pray": typeof AppsRakatPrayRoute
  "/apps/work-timer/settings": typeof AppsWorkTimerSettingsRoute
  "/apps/work-timer/total": typeof AppsWorkTimerTotalRoute
  "/apps/rakat/": typeof AppsRakatIndexRoute
  "/apps/work-timer/": typeof AppsWorkTimerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/apps/rakat"
    | "/apps/work-timer"
    | "/apps/nebula"
    | "/apps/pick-one"
    | "/apps/promptor"
    | "/apps/rakat/choose"
    | "/apps/rakat/pray"
    | "/apps/work-timer/settings"
    | "/apps/work-timer/total"
    | "/apps/rakat/"
    | "/apps/work-timer/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/apps/nebula"
    | "/apps/pick-one"
    | "/apps/promptor"
    | "/apps/rakat/choose"
    | "/apps/rakat/pray"
    | "/apps/work-timer/settings"
    | "/apps/work-timer/total"
    | "/apps/rakat"
    | "/apps/work-timer"
  id:
    | "__root__"
    | "/"
    | "/apps/rakat"
    | "/apps/work-timer"
    | "/apps/nebula"
    | "/apps/pick-one"
    | "/apps/promptor"
    | "/apps/rakat/choose"
    | "/apps/rakat/pray"
    | "/apps/work-timer/settings"
    | "/apps/work-timer/total"
    | "/apps/rakat/"
    | "/apps/work-timer/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRakatRouteRoute: typeof AppsRakatRouteRouteWithChildren
  AppsWorkTimerRouteRoute: typeof AppsWorkTimerRouteRouteWithChildren
  AppsNebulaRoute: typeof AppsNebulaRoute
  AppsPickOneRoute: typeof AppsPickOneRoute
  AppsPromptorRoute: typeof AppsPromptorRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/promptor": {
      id: "/apps/promptor"
      path: "/apps/promptor"
      fullPath: "/apps/promptor"
      preLoaderRoute: typeof AppsPromptorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/pick-one": {
      id: "/apps/pick-one"
      path: "/apps/pick-one"
      fullPath: "/apps/pick-one"
      preLoaderRoute: typeof AppsPickOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/nebula": {
      id: "/apps/nebula"
      path: "/apps/nebula"
      fullPath: "/apps/nebula"
      preLoaderRoute: typeof AppsNebulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/work-timer": {
      id: "/apps/work-timer"
      path: "/apps/work-timer"
      fullPath: "/apps/work-timer"
      preLoaderRoute: typeof AppsWorkTimerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/rakat": {
      id: "/apps/rakat"
      path: "/apps/rakat"
      fullPath: "/apps/rakat"
      preLoaderRoute: typeof AppsRakatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apps/work-timer/": {
      id: "/apps/work-timer/"
      path: "/"
      fullPath: "/apps/work-timer/"
      preLoaderRoute: typeof AppsWorkTimerIndexRouteImport
      parentRoute: typeof AppsWorkTimerRouteRoute
    }
    "/apps/rakat/": {
      id: "/apps/rakat/"
      path: "/"
      fullPath: "/apps/rakat/"
      preLoaderRoute: typeof AppsRakatIndexRouteImport
      parentRoute: typeof AppsRakatRouteRoute
    }
    "/apps/work-timer/total": {
      id: "/apps/work-timer/total"
      path: "/total"
      fullPath: "/apps/work-timer/total"
      preLoaderRoute: typeof AppsWorkTimerTotalRouteImport
      parentRoute: typeof AppsWorkTimerRouteRoute
    }
    "/apps/work-timer/settings": {
      id: "/apps/work-timer/settings"
      path: "/settings"
      fullPath: "/apps/work-timer/settings"
      preLoaderRoute: typeof AppsWorkTimerSettingsRouteImport
      parentRoute: typeof AppsWorkTimerRouteRoute
    }
    "/apps/rakat/pray": {
      id: "/apps/rakat/pray"
      path: "/pray"
      fullPath: "/apps/rakat/pray"
      preLoaderRoute: typeof AppsRakatPrayRouteImport
      parentRoute: typeof AppsRakatRouteRoute
    }
    "/apps/rakat/choose": {
      id: "/apps/rakat/choose"
      path: "/choose"
      fullPath: "/apps/rakat/choose"
      preLoaderRoute: typeof AppsRakatChooseRouteImport
      parentRoute: typeof AppsRakatRouteRoute
    }
  }
}

interface AppsRakatRouteRouteChildren {
  AppsRakatChooseRoute: typeof AppsRakatChooseRoute
  AppsRakatPrayRoute: typeof AppsRakatPrayRoute
  AppsRakatIndexRoute: typeof AppsRakatIndexRoute
}

const AppsRakatRouteRouteChildren: AppsRakatRouteRouteChildren = {
  AppsRakatChooseRoute: AppsRakatChooseRoute,
  AppsRakatPrayRoute: AppsRakatPrayRoute,
  AppsRakatIndexRoute: AppsRakatIndexRoute,
}

const AppsRakatRouteRouteWithChildren = AppsRakatRouteRoute._addFileChildren(
  AppsRakatRouteRouteChildren,
)

interface AppsWorkTimerRouteRouteChildren {
  AppsWorkTimerSettingsRoute: typeof AppsWorkTimerSettingsRoute
  AppsWorkTimerTotalRoute: typeof AppsWorkTimerTotalRoute
  AppsWorkTimerIndexRoute: typeof AppsWorkTimerIndexRoute
}

const AppsWorkTimerRouteRouteChildren: AppsWorkTimerRouteRouteChildren = {
  AppsWorkTimerSettingsRoute: AppsWorkTimerSettingsRoute,
  AppsWorkTimerTotalRoute: AppsWorkTimerTotalRoute,
  AppsWorkTimerIndexRoute: AppsWorkTimerIndexRoute,
}

const AppsWorkTimerRouteRouteWithChildren =
  AppsWorkTimerRouteRoute._addFileChildren(AppsWorkTimerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRakatRouteRoute: AppsRakatRouteRouteWithChildren,
  AppsWorkTimerRouteRoute: AppsWorkTimerRouteRouteWithChildren,
  AppsNebulaRoute: AppsNebulaRoute,
  AppsPickOneRoute: AppsPickOneRoute,
  AppsPromptorRoute: AppsPromptorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
